In [4]:
import pandas as pd

raw_data = pd.read_csv('ENFR 2018 - Base usuario.txt', sep = '|')
df = raw_data.copy()

# Obtenemos todas las columnas que empiezan con BH
cols_BH = df.columns[df.columns.str.startswith('bh')].tolist()

# Separamos en subgrupos
cols_BHCV = df.columns[df.columns.str.startswith('bhcv')].tolist() # Vivienda
cols_BHHO = df.columns[df.columns.str.startswith('bhho')].tolist() # Hogar
cols_BHIH = df.columns[df.columns.str.startswith('bhih')].tolist() # Ingresos
cols_BHCH = df.columns[df.columns.str.startswith('bhch')].tolist() # Componentes
cols_BHSL = df.columns[df.columns.str.startswith('bhsl')].tolist() # Situacion Laboral Jefe 

# Identificador y Ubicacion
cols_ID_UB = ['id', 'cod_provincia', 'region', 'tamanio_aglomerado', 'aglomerado', 'localidades_150', 'submuestra']

# Añadimos a Características del Hogar
cols_BHHO.extend(['tipo_hogar'])

# Añadimos a Ingresos del Hogar
cols_BHIH.extend(['rango_ingreso', 'quintil_uc'])

# Añadimos a Componentes del Hogar 
cols_BHCH.extend([
    'cant_componentes', 'miembros_18', 'rango_edad_j', 
    'nivel_instruccion_j', 'nivel_instruccion_agrupado_j', 'cobertura_salud_j'
])

# Añadimos a Situación Laboral del Jefe del Hogar
cols_BHSL.extend(['condicion_actividad_j'])

cols_agrupadas_bh = [col for col in cols_BH if col in (cols_BHCV + cols_BHHO + cols_BHIH + cols_BHCH + cols_BHSL)]
cols_afuera = [col for col in cols_BH if col not in cols_agrupadas_bh]

# Diccionario 
categorias_columnas = {
    "Identificación y Ubicación (ID/UB)": cols_ID_UB,
    "Características de la Vivienda (BHCV)": cols_BHCV,
    "Características del Hogar (BHHO)": cols_BHHO,
    "Ingresos del Hogar (BHIH)": cols_BHIH,
    "Componentes del hogar (BHCH)": cols_BHCH,
    "Situacion Laboral del Jefe del Hogar": cols_BHSL,
    "SOBRANTES (BH sin clasificar)": cols_afuera
}
# Print
for nombre_categoria, columnas in categorias_columnas.items():
    print(f"--- {nombre_categoria} ---")
    print(f"Cantidad encontradas: {len(columnas)}")
    print(f"Columnas: {columnas}")
    print()

--- Identificación y Ubicación (ID/UB) ---
Cantidad encontradas: 7
Columnas: ['id', 'cod_provincia', 'region', 'tamanio_aglomerado', 'aglomerado', 'localidades_150', 'submuestra']

--- Características de la Vivienda (BHCV) ---
Cantidad encontradas: 11
Columnas: ['bhcv01', 'bhcv02', 'bhcv03', 'bhcv04', 'bhcv05', 'bhcv06', 'bhcv07', 'bhcv08', 'bhcv09', 'bhcv10', 'bhcv11']

--- Características del Hogar (BHHO) ---
Cantidad encontradas: 4
Columnas: ['bhho01', 'bhho02', 'bhho03', 'tipo_hogar']

--- Ingresos del Hogar (BHIH) ---
Cantidad encontradas: 5
Columnas: ['bhih01', 'bhih01_02', 'bhih03', 'rango_ingreso', 'quintil_uc']

--- Componentes del hogar (BHCH) ---
Cantidad encontradas: 27
Columnas: ['bhch03_j', 'bhch04_j', 'bhch05_j', 'bhch10_01_j', 'bhch10_02_j', 'bhch10_03_j', 'bhch10_04_j', 'bhch10_05_j', 'bhch10_06_j', 'bhch10_99_j', 'bhch02', 'bhch03', 'bhch04', 'bhch05', 'bhch10_01', 'bhch10_02', 'bhch10_03', 'bhch10_04', 'bhch10_05', 'bhch10_06', 'bhch10_99', 'cant_componentes', 'miembros_18', 'rango_edad_j', 'nivel_instruccion_j', 'nivel_instruccion_agrupado_j', 'cobertura_salud_j']

--- Situacion Laboral del Jefe del Hogar ---
Cantidad encontradas: 7
Columnas: ['bhsl01', 'bhsl02', 'bhsl03', 'bhsl04', 'bhsl05', 'bhsl06', 'condicion_actividad_j']

--- SOBRANTES (BH sin clasificar) ---
Cantidad encontradas: 0
Columnas: []

# Identificacion y Ubicacion

In [ ]:
df_id_ub=df[cols_ID_UB].copy()

df_id_ub.head()

,id,cod_provincia,region,tamanio_aglomerado,aglomerado,localidades_150,submuestra
0,1128639,2,1,1,1,1,1
1,1709939,2,1,1,1,1,0
2,6874130,2,1,1,1,1,0
3,10319375,2,1,1,1,1,1
4,11140857,2,1,1,1,1,0

# Vivienda

In [ ]:
df_vivienda=df[['id'] +cols_BHCV].copy()

df_vivienda.head()

,id,bhcv01,bhcv02,bhcv03,bhcv04,bhcv05,bhcv06,bhcv07,bhcv08,bhcv09,bhcv10,bhcv11
0,1128639,3,2,1,2,1,1,1,1,1,1.0,1.0
1,1709939,1,4,1,2,1,1,1,1,1,1.0,1.0
2,6874130,3,2,1,2,1,1,1,1,1,1.0,1.0
3,10319375,3,1,1,2,1,4,1,1,1,1.0,1.0
4,11140857,3,3,1,2,1,1,1,1,1,1.0,1.0

# Hogar

In [8]:
df_hogar=df[["id"]+cols_BHHO].copy()

df_hogar.head()

         id  bhho01  bhho02  bhho03  tipo_hogar
0   1128639     1.0       2       1           2
1   1709939     1.0       4       3           4
2   6874130     1.0       2       1           2
3  10319375     1.0       1       1           1
4  11140857     1.0       3       2           8

# Ingresos

In [ ]:
df_ingresos = df[['id'] + cols_BHIH].copy()

df_ingresos.head()

# Componentes

In [9]:
df_componentes = df[['id'] + cols_BHCH].copy()

df_componentes.head()

,id,bhch03_j,bhch04_j,bhch05_j,bhch10_01_j,bhch10_02_j,bhch10_03_j,bhch10_04_j,bhch10_05_j,bhch10_06_j,...,bhch10_04,bhch10_05,bhch10_06,bhch10_99,cant_componentes,miembros_18,rango_edad_j,nivel_instruccion_j,nivel_instruccion_agrupado_j,cobertura_salud_j
0,1128639,2,28,6,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,2,2,2,7,3,1
1,1709939,1,54,2,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3,3,4,7,3,1
2,6874130,1,41,6,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2,2,3,7,3,1
3,10319375,2,64,3,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,1,4,7,3,1
4,11140857,1,25,6,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,2,2,2,6,3,2

# Situacion Laboral

In [10]:
df_sit_laboral = df[['id'] + cols_BHSL].copy()

df_sit_laboral.head()

,id,bhsl01,bhsl02,bhsl03,bhsl04,bhsl05,bhsl06,condicion_actividad_j
0,1128639,1,NaN,NaN,NaN,NaN,1.0,1
1,1709939,1,NaN,NaN,NaN,NaN,2.0,1
2,6874130,1,NaN,NaN,NaN,NaN,2.0,1
3,10319375,1,NaN,NaN,NaN,NaN,3.0,1
4,11140857,1,NaN,NaN,NaN,NaN,2.0,1